### ISSUE TITLE
command 'vscdb-workspace-storage-cleanup.run' not found

### ISSUE THREAD

**Issue by tjx666** [8LWXpg/vscdb-workspace-storage-cleanup#1]
![image](https://github.com/8LWXpg/vscdb-workspace-storage-cleanup/assets/41773861/50cf2129-d89c-4301-a16f-8192d6e8ecad)

version: v1.0.3

**Comment by 8LWXpg** [comment]
I've pushed v1.0.4 prerelease, can you test it out?

**Comment by tjx666** [comment]
works fine.
