### ISSUE TITLE
Feature: add cleanup function for recently opened files

### ISSUE THREAD

**Issue by MasouShizuka** [8LWXpg/vscdb-workspace-storage-cleanup#2]
Thank you for your plugin with command to clean recently opened folders.
Now I can use your plugin and plugin `Workspace Storage Cleanup` to manage the workspace.

Can you add a command to clean recently opened files?
Maybe this feature doesn't match the name of the plugin?

**Comment by 8LWXpg** [comment]
now I need to add another command for files, so it's needed to change command titles (or even display name?)

here's what I came up with:
`"vscdb Cleanup: Workspace Storage"` and `"vscdb Cleanup: Recently Opened Files"`

what's your thought on these names?

**Comment by MasouShizuka** [comment]
More accurately, perhaps it should be named according to the official name of vscode: `vscdb Cleanup: Recently Opened Folders` and `vscdb Cleanup: Recently Opened Files`.
![image](https://github.com/8LWXpg/vscdb-workspace-storage-cleanup/assets/44764707/e478bd4b-d278-4121-a58c-f8f70f81d677)
![image](https://github.com/8LWXpg/vscdb-workspace-storage-cleanup/assets/44764707/600c2c4f-a992-41d2-b50e-a713600b3d9c)

But your plugin is mainly to solve the `PowerToys` workspace problem, so I think your naming is okay.

**Comment by 8LWXpg** [comment]
Thanks for the opinion, I think `Recently Opened Folders` is better.

**Comment by 8LWXpg** [comment]
[v2.0.0](https://marketplace.visualstudio.com/items?itemName=8LWXpg.vscdb-workspace-storage-cleanup) is released

**Comment by MasouShizuka** [comment]
After the update, the delete button in the `vscdb Cleanup: Recently Opened Folders` command pane does not work.

In addition, when using the command `vscdb Cleanup: Recently Opened Files` to delete, a notification in the lower right corner will display:
![image](https://github.com/8LWXpg/vscdb-workspace-storage-cleanup/assets/44764707/9363f630-6ca8-46ef-a65d-380e676fa345)

**Comment by 8LWXpg** [comment]
fixed in v2.0.1
